language: go
env:
  matrix:
  - GOPATH=$TRAVIS_BUILD_DIR/gosrc
  global:
  - targetSlug: aanc/aanc.github.io
  - secure: cmzgNjbdAHj357epzZ4l2u5X9Y9eVxKj3jQ6gHPJpw6tObavbCM6/M67b1o3aaPnVjJMnZlIZ8pt4yY5n8ycAmfc0nUo4qlon6IbrfZxO1Oro+yNevtsZZn/pp3k1yt/H7wyoSum+dyw/I/SJYdw6kx6kVZDw0jUUJcGlSuQ6h1/R5xtLvUKfWG3mp6d1pzyCHWhY5X0FcTmXXtLOWP2jULVzQ0hpIGJh3x14uyFuwfw77eMYkH9uq8r+9g/fNkLCkxA8Q+wnhhcUy7t7ZYCaC3IsPjde9WxgpXlUMJ3qR33NLUjFrA0fVH7PTUaa7taeLONfF6bPoCf56OOq2rXBPeRWSkqiPr2pBr01K7hzDphJMul1nSedayTAGhnJq7oeIpG4JME0zmZHW3yqvKLNCEzcy1AadGMT37M/QoGMFu1a4jXcgxlX5++Hnyo0yxdGFDmsEqYKay0/s8+YweJvk1Vvt0KMC/l+T1ptN2izfiYlf/7KGyM/jU1nyYfg07nBRSEnMFvy9NsWwINDHZBTIR6ypujSzDGsKxwCFpV/GCRQqktvHDSJAPFXMZE/FiQBQWIl5lwqK3J9f6GX1mCuAGnU8lGRLfshxUMetPXjpNeRL9J3sCTDAG1Ya3chBjvYbvtX6OFHfGyoQJwuFL6xOawKMM7s09HaJuVD5sN844=
install:
- mkdir -p "$TRAVIS_BUILD_DIR/gosrc"
- go get -v github.com/spf13/hugo
script: "./build.sh"
