language: go
env:
  matrix:
  - GOPATH=$TRAVIS_BUILD_DIR/gosrc
  global:
install:
- mkdir -p "$TRAVIS_BUILD_DIR/gosrc"
- go get -v github.com/spf13/hugo
script: 
- make build
- [[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_BRANCH == master ]] && make deploy
