baseurl = "https://aanc.github.io"
title = "nknu.net"
theme = "hugo-banality-theme"
canonifyurls = "true"

[permalinks]
  post = "/:slug/"

[params]
  description = "Embrace your inner Geek"
  author = "Adrien Anceau"
  bio = "Geek, gamer, photography enthusiast, passionate about technology, automation and food."
  gravatar = "0cadf2f30a2d888cc46b5497292f8ff5"

  disqus = "nknu"
  twitter = "aaadrieeen"
  facebook = "adrien.anceau"
  github = "aanc"
